[workspace]

members = [
  "gen-bindings",
  "keygen",
  "polygon-zkevm-adaptor",
  "zkevm",
  "zkevm-contract-bindings",
]

# Patch Jellyfish until the crypto_kx compatibility issue is fixed
[patch."https://github.com/EspressoSystems/jellyfish"]
jf-primitives = { git = "https://github.com/EspressoSystems//jellyfish", branch = "hotshot-compat" }
jf-relation = { git = "https://github.com/EspressoSystems//jellyfish", branch = "hotshot-compat" }
jf-utils = { git = "https://github.com/EspressoSystems//jellyfish", branch = "hotshot-compat" }
