[workspace]

members = [
  "gen-bindings",
  "keygen",
  "polygon-zkevm-adaptor",
  "zkevm",
  "zkevm-contract-bindings",
]

[patch."https://github.com/EspressoSystems/espresso-sequencer"]
"sequencer-utils" = { path = "../espresso-sequencer/utils" }
