version: "3"

networks:
  default:
    name: espresso-sequencer

services:

  polygon-zkevm-1-adaptor:
    extends:
      file: services.yaml
      service: adaptor
    ports:
      - "$ESPRESSO_ZKEVM_1_ADAPTOR_RPC_PORT:$ESPRESSO_ZKEVM_1_ADAPTOR_RPC_PORT"
      - "$ESPRESSO_ZKEVM_1_ADAPTOR_QUERY_PORT:$ESPRESSO_ZKEVM_1_ADAPTOR_QUERY_PORT"
    environment:
      - ESPRESSO_ZKEVM_ADAPTOR_RPC_PORT=$ESPRESSO_ZKEVM_1_ADAPTOR_RPC_PORT
      - ESPRESSO_ZKEVM_ADAPTOR_QUERY_PORT=$ESPRESSO_ZKEVM_1_ADAPTOR_QUERY_PORT
    profiles:
      - zkevm1
      - zkevm1-preconfirmations

  zkevm-1-aggregator:
    extends:
      file: services.yaml
      service: aggregator
    environment:
      - ZKEVM_NODE_ETHERMAN_POEADDR=$ESPRESSO_ZKEVM_1_ROLLUP_ADDRESS
      - ZKEVM_NODE_ETHERMAN_MATICADDR=$ESPRESSO_ZKEVM_1_MATIC_ADDRESS
      - ZKEVM_NODE_ETHERMAN_GLOBALEXITROOTMANAGERADDR=$ESPRESSO_ZKEVM_1_GER_ADDRESS
      - ZKEVM_NODE_ETHERMAN_URL=$ESPRESSO_ZKEVM_L1_PROVIDER
      - ZKEVM_NODE_ETHERMAN_HOTSHOTQUERYSERVICEURL=$ESPRESSO_ZKEVM_1_ADAPTOR_QUERY_URL
      - ZKEVM_NODE_ETHERMAN_HOTSHOTADDR=$ESPRESSO_SEQUENCER_HOTSHOT_ADDRESS
      - ZKEVM_NODE_AGGREGATOR_SENDERADDRESS=0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
      - ZKEVM_NODE_MTCLIENT_URI=$ESPRESSO_ZKEVM_1_MTCLIENT_URI
      - ZKEVM_NODE_EXECUTOR_URI=$ESPRESSO_ZKEVM_1_EXECUTOR_URI
    depends_on:
      zkevm-1-prover:
        condition: service_healthy
      # Avoid running DB migrations at the same time:
      zkevm-1-permissionless-node:
        condition: service_healthy
    profiles:
      - zkevm1

  zkevm-1-state-db:
    extends:
      file: services.yaml
      service: state-db
    profiles:
      - zkevm1

  zkevm-1-preconfirmations-state-db:
    extends:
      file: services.yaml
      service: state-db
    profiles:
      - zkevm1-preconfirmations

  zkevm-1-prover:
    extends:
      file: services.yaml
      service: prover
    volumes:
      - ./zkevm-node/test/config/test.prover.1.config.json:/usr/src/app/config.json
    depends_on:
      zkevm-1-state-db:
        condition: service_healthy
    profiles:
      - zkevm1

  zkevm-1-preconfirmations-prover:
    extends:
      file: services.yaml
      service: prover
    volumes:
      - ./zkevm-node/test/config/test.prover.1.config.json:/usr/src/app/config.json
    depends_on:
      zkevm-1-preconfirmations-state-db:
        condition: service_healthy
    profiles:
      - zkevm1-preconfirmations

  zkevm-1-permissionless-node:
    extends:
      file: services.yaml
      service: permissionless-node
    ports:
      - $ESPRESSO_ZKEVM_1_L2_PORT:$ESPRESSO_ZKEVM_1_L2_PORT
      - $ESPRESSO_ZKEVM_1_L2_PORT_WS:$ESPRESSO_ZKEVM_1_L2_PORT_WS
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-1-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-1-state-db
      - ZKEVM_NODE_RPC_PORT=$ESPRESSO_ZKEVM_1_L2_PORT
      - ZKEVM_NODE_RPC_WEBSOCKETS_PORT=$ESPRESSO_ZKEVM_1_L2_PORT_WS
      - ZKEVM_NODE_RPC_SEQUENCERNODEURI=$ESPRESSO_ZKEVM_1_ADAPTOR_RPC_URL
      - ZKEVM_NODE_ETHERMAN_URL=$ESPRESSO_ZKEVM_L1_PROVIDER
      - ZKEVM_NODE_ETHERMAN_POEADDR=$ESPRESSO_ZKEVM_1_ROLLUP_ADDRESS
      - ZKEVM_NODE_ETHERMAN_MATICADDR=$ESPRESSO_ZKEVM_1_MATIC_ADDRESS
      - ZKEVM_NODE_ETHERMAN_GLOBALEXITROOTMANAGERADDR=$ESPRESSO_ZKEVM_1_GER_ADDRESS
      - ZKEVM_NODE_ETHERMAN_HOTSHOTQUERYSERVICEURL=$ESPRESSO_ZKEVM_1_ADAPTOR_QUERY_URL
      - ZKEVM_NODE_ETHERMAN_HOTSHOTADDR=$ESPRESSO_SEQUENCER_HOTSHOT_ADDRESS
      - ZKEVM_NODE_ETHERMAN_GENESISHOTSHOTBLOCKNUMBER=$ESPRESSO_ZKEVM_1_GENESIS_HOTSHOT_BLOCK_NUMBER
      - ZKEVM_NODE_SYNCHRONIZER_GENBLOCKNUMBER=$ESPRESSO_ZKEVM_1_GENESIS_BLOCK_NUMBER
      - ZKEVM_NODE_SYNCHRONIZER_IGNOREGENBLOCKNUMBERCHECK=$ESPRESSO_ZKEVM_IGNORE_GEN_BLOCK_NUMBER_CHECK
      - ZKEVM_NODE_MTCLIENT_URI=$ESPRESSO_ZKEVM_1_MTCLIENT_URI
      - ZKEVM_NODE_EXECUTOR_URI=$ESPRESSO_ZKEVM_1_EXECUTOR_URI
    depends_on:
      zkevm-1-state-db:
        condition: service_healthy
    profiles:
      - zkevm1

  zkevm-1-preconfirmations-node:
    extends:
      file: services.yaml
      service: permissionless-node
    ports:
      - $ESPRESSO_ZKEVM_1_PRECONFIRMATIONS_L2_PORT:$ESPRESSO_ZKEVM_1_PRECONFIRMATIONS_L2_PORT
      - $ESPRESSO_ZKEVM_1_PRECONFIRMATIONS_L2_PORT_WS:$ESPRESSO_ZKEVM_1_PRECONFIRMATIONS_L2_PORT_WS
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-1-preconfirmations-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-1-preconfirmations-state-db
      - ZKEVM_NODE_RPC_PORT=$ESPRESSO_ZKEVM_1_PRECONFIRMATIONS_L2_PORT
      - ZKEVM_NODE_RPC_WEBSOCKETS_PORT=$ESPRESSO_ZKEVM_1_PRECONFIRMATIONS_L2_PORT_WS
      - ZKEVM_NODE_RPC_SEQUENCERNODEURI=$ESPRESSO_ZKEVM_1_ADAPTOR_RPC_URL
      - ZKEVM_NODE_ETHERMAN_URL=$ESPRESSO_ZKEVM_L1_PROVIDER
      - ZKEVM_NODE_ETHERMAN_POEADDR=$ESPRESSO_ZKEVM_1_ROLLUP_ADDRESS
      - ZKEVM_NODE_ETHERMAN_MATICADDR=$ESPRESSO_ZKEVM_1_MATIC_ADDRESS
      - ZKEVM_NODE_ETHERMAN_GLOBALEXITROOTMANAGERADDR=$ESPRESSO_ZKEVM_1_GER_ADDRESS
      - ZKEVM_NODE_ETHERMAN_HOTSHOTQUERYSERVICEURL=$ESPRESSO_ZKEVM_1_ADAPTOR_QUERY_URL
      - ZKEVM_NODE_ETHERMAN_HOTSHOTADDR=$ESPRESSO_SEQUENCER_HOTSHOT_ADDRESS
      - ZKEVM_NODE_ETHERMAN_GENESISHOTSHOTBLOCKNUMBER=$ESPRESSO_ZKEVM_1_GENESIS_HOTSHOT_BLOCK_NUMBER
      - ZKEVM_NODE_SYNCHRONIZER_GENBLOCKNUMBER=$ESPRESSO_ZKEVM_1_GENESIS_BLOCK_NUMBER
      - ZKEVM_NODE_SYNCHRONIZER_PRECONFIRMATIONSSYNCINTERVAL=$ESPRESSO_ZKEVM_1_PRECONFIRMATIONS_SYNC_INTERVAL
      - ZKEVM_NODE_SYNCHRONIZER_IGNOREGENBLOCKNUMBERCHECK=$ESPRESSO_ZKEVM_IGNORE_GEN_BLOCK_NUMBER_CHECK
      - ZKEVM_NODE_MTCLIENT_URI=$ESPRESSO_ZKEVM_1_PRECONFIRMATIONS_MTCLIENT_URI
      - ZKEVM_NODE_EXECUTOR_URI=$ESPRESSO_ZKEVM_1_PRECONFIRMATIONS_EXECUTOR_URI
    depends_on:
      zkevm-1-preconfirmations-state-db:
        condition: service_healthy
    profiles:
      - zkevm1-preconfirmations

  zkevm-1-eth-tx-manager:
    extends:
      file: services.yaml
      service: eth-tx-manager
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-1-state-db
      - ZKEVM_NODE_ETHERMAN_POEADDR=$ESPRESSO_ZKEVM_1_ROLLUP_ADDRESS
      - ZKEVM_NODE_ETHERMAN_MATICADDR=$ESPRESSO_ZKEVM_1_MATIC_ADDRESS
      - ZKEVM_NODE_ETHERMAN_GLOBALEXITROOTMANAGERADDR=$ESPRESSO_ZKEVM_1_GER_ADDRESS
      - ZKEVM_NODE_ETHERMAN_URL=$ESPRESSO_ZKEVM_L1_PROVIDER
      - ZKEVM_NODE_ETHERMAN_HOTSHOTQUERYSERVICEURL=$ESPRESSO_ZKEVM_1_ADAPTOR_QUERY_URL
      - ZKEVM_NODE_ETHERMAN_HOTSHOTADDR=$ESPRESSO_SEQUENCER_HOTSHOT_ADDRESS
      - ZKEVM_NODE_MTCLIENT_URI=$ESPRESSO_ZKEVM_1_MTCLIENT_URI
      - ZKEVM_NODE_EXECUTOR_URI=$ESPRESSO_ZKEVM_1_EXECUTOR_URI
      - ZKEVM_NODE_ETHTXMANAGER_POLLINGINTERVAL=$ESPRESSO_ZKEVM_ETH_TX_MANAGER_POLLING_INTERVAL
    depends_on:
      zkevm-1-permissionless-node:
        condition: service_healthy
    profiles:
      - zkevm1

  zkevm-1-faucet:
    extends:
      file: services.yaml
      service: faucet
    ports:
      - $ESPRESSO_ZKEVM_1_FAUCET_PORT:$ESPRESSO_ZKEVM_1_FAUCET_PORT
    environment:
      - ESPRESSO_DISCORD_FAUCET_PORT=$ESPRESSO_ZKEVM_1_FAUCET_PORT
      - ESPRESSO_DISCORD_FAUCET_WEB3_PROVIDER_URL_WS=$ESPRESSO_ZKEVM_1_FAUCET_WEB3_PROVIDER_URL_WS
      - ESPRESSO_DISCORD_FAUCET_WEB3_PROVIDER_URL_HTTP=$ESPRESSO_ZKEVM_1_FAUCET_WEB3_PROVIDER_URL_HTTP
    depends_on:
      zkevm-1-permissionless-node:
        condition: service_healthy
    profiles:
      - zkevm1
