version: "3"
services:
  cdn-server:
    image: ghcr.io/espressosystems/espresso-sequencer/cdn-server:main
    ports:
      - "$ESPRESSO_CDN_SERVER_PORT:$ESPRESSO_CDN_SERVER_PORT"
    environment:
      - ESPRESSO_CDN_SERVER_PORT
      - ESPRESSO_CDN_SERVER_NUM_NODES=5
      - ESPRESSO_CDN_SERVER_START_DELAY=5s
      - ESPRESSO_CDN_SERVER_MAX_PROPOSE_TIME
      - RUST_LOG
      - RUST_LOG_FORMAT

  sequencer0:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    # Run consensus *plus* the sequencer API server.
    command: /bin/sequencer -- api
    ports:
      - "$ESPRESSO_SEQUENCER_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    environment:
      - ESPRESSO_SEQUENCER_CDN_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      cdn-server:
        condition: service_started
      zkevm-mock-l1-network:
        condition: service_healthy
  sequencer1:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    # Run consensus *plus* the commitment task to post commitments to the
    # hotshot contract.
    command: /bin/sequencer -- commitment-task
    environment:
      - ESPRESSO_SEQUENCER_CDN_URL
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_HOTSHOT_ADDRESS
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_QUERY_SERVICE_URL
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      - cdn-server
      - sequencer0
  sequencer2:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    environment:
      - ESPRESSO_SEQUENCER_CDN_URL
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      - cdn-server
      - sequencer0
  sequencer3:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    environment:
      - ESPRESSO_SEQUENCER_CDN_URL
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      - cdn-server
      - sequencer0
  sequencer4:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    environment:
      - ESPRESSO_SEQUENCER_CDN_URL
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      - cdn-server
      - sequencer0

  polygon-zkevm-1-adaptor:
    image: ghcr.io/espressosystems/espresso-polygon-zkevm-demo/polygon-zkevm-adaptor:main
    ports:
      - "$ESPRESSO_ZKEVM_1_ADAPTOR_RPC_PORT:$ESPRESSO_ZKEVM_1_ADAPTOR_RPC_PORT"
      - "$ESPRESSO_ZKEVM_1_ADAPTOR_QUERY_PORT:$ESPRESSO_ZKEVM_1_ADAPTOR_QUERY_PORT"
    environment:
      - ESPRESSO_SEQUENCER_URL
      - ESPRESSO_ZKEVM_L1_PROVIDER
      - ESPRESSO_ZKEVM_ROLLUP_ADDRESS=$ESPRESSO_ZKEVM_1_ROLLUP_ADDRESS
      - ESPRESSO_ZKEVM_MATIC_ADDRESS=$ESPRESSO_ZKEVM_1_MATIC_ADDRESS
      - ESPRESSO_ZKEVM_ADAPTOR_RPC_PORT=$ESPRESSO_ZKEVM_1_ADAPTOR_RPC_PORT
      - ESPRESSO_ZKEVM_ADAPTOR_QUERY_PORT=$ESPRESSO_ZKEVM_1_ADAPTOR_QUERY_PORT
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      sequencer0:
        condition: service_started
    healthcheck:
      test: "curl http://localhost:$ESPRESSO_ZKEVM_1_ADAPTOR_QUERY_PORT"
      interval: 1s
      timeout: 0.5s
      retries: 120
    profiles:
      - zkevm1
      - zkevm1-preconfirmations

  polygon-zkevm-2-adaptor:
    image: ghcr.io/espressosystems/espresso-polygon-zkevm-demo/polygon-zkevm-adaptor:main
    ports:
      - "$ESPRESSO_ZKEVM_2_ADAPTOR_RPC_PORT:$ESPRESSO_ZKEVM_2_ADAPTOR_RPC_PORT"
      - "$ESPRESSO_ZKEVM_2_ADAPTOR_QUERY_PORT:$ESPRESSO_ZKEVM_2_ADAPTOR_QUERY_PORT"
    environment:
      - ESPRESSO_SEQUENCER_URL
      - ESPRESSO_ZKEVM_L1_PROVIDER
      - ESPRESSO_ZKEVM_ROLLUP_ADDRESS=$ESPRESSO_ZKEVM_2_ROLLUP_ADDRESS
      - ESPRESSO_ZKEVM_MATIC_ADDRESS=$ESPRESSO_ZKEVM_2_MATIC_ADDRESS
      - ESPRESSO_ZKEVM_ADAPTOR_RPC_PORT=$ESPRESSO_ZKEVM_2_ADAPTOR_RPC_PORT
      - ESPRESSO_ZKEVM_ADAPTOR_QUERY_PORT=$ESPRESSO_ZKEVM_2_ADAPTOR_QUERY_PORT
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      sequencer0:
        condition: service_started
    healthcheck:
      test: "curl http://localhost:$ESPRESSO_ZKEVM_2_ADAPTOR_QUERY_PORT"
      interval: 1s
      timeout: 0.5s
      retries: 120
    profiles:
      - zkevm2
      - zkevm2-preconfirmations
