version: "3"
services:
  cdn-server:
    image: ghcr.io/espressosystems/espresso-sequencer/cdn-server:main
    ports:
      - "$ESPRESSO_CDN_SERVER_PORT:$ESPRESSO_CDN_SERVER_PORT"
    environment:
      - ESPRESSO_CDN_SERVER_PORT
      - ESPRESSO_CDN_SERVER_NUM_NODES=5
      - ESPRESSO_CDN_SERVER_START_DELAY=5s
      - RUST_LOG

  sequencer0:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    # Run consensus *plus* the commitment task to post commitments to the
    # hotshot contract.
    command: /bin/sequencer commitment-task
    ports:
      - "$ESPRESSO_SEQUENCER_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    environment:
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_CDN_URL
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_HOTSHOT_ADDRESS
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - QUERY_SERVICE_URL
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      - cdn-server
  sequencer1:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER1_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    environment:
      - ESPRESSO_SEQUENCER_CDN_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      - cdn-server
      - sequencer0
  sequencer2:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER2_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    environment:
      - ESPRESSO_SEQUENCER_CDN_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      - cdn-server
      - sequencer0
  sequencer3:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER3_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    environment:
      - ESPRESSO_SEQUENCER_CDN_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      - cdn-server
      - sequencer0
  sequencer4:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER4_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    environment:
      - ESPRESSO_SEQUENCER_CDN_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      - cdn-server
      - sequencer0

  hermez-adaptor:
    image: ghcr.io/espressosystems/espresso-polygon-zkevm-demo/hermez-adaptor:main
    ports:
      - "$ESPRESSO_ZKEVM_ADAPTOR_RPC_PORT:$ESPRESSO_ZKEVM_ADAPTOR_RPC_PORT"
      - "$ESPRESSO_ZKEVM_ADAPTOR_QUERY_PORT:$ESPRESSO_ZKEVM_ADAPTOR_QUERY_PORT"
    environment:
      - ESPRESSO_SEQUENCER_URL
      - ESPRESSO_ZKEVM_L1_PROVIDER
      - ESPRESSO_ZKEVM_ROLLUP_ADDRESS
      - ESPRESSO_ZKEVM_MATIC_ADDRESS
      - ESPRESSO_ZKEVM_SEQUENCER_MNEMONIC
      - ESPRESSO_ZKEVM_ADAPTOR_RPC_PORT
      - ESPRESSO_ZKEVM_ADAPTOR_QUERY_PORT
      - RUST_LOG
    depends_on:
      - sequencer0
