version: "3"
services:
  zkevm-mock-l1-network:
    image: ghcr.io/espressosystems/espresso-polygon-zkevm-demo/geth-with-contracts:main
    command: [
      "--http",
      "--http.api",
      "admin,eth,debug,miner,net,txpool,personal,web3",
      "--http.addr",
      "0.0.0.0",
      "--http.port",
      "$ESPRESSO_ZKEVM_L1_PORT",
      "--http.corsdomain",
      "*",
      "--http.vhosts" ,
      "*",
      "--ws",
      "--ws.origins",
      "*",
      "--ws.addr",
      "0.0.0.0",
      "--dev",
      "--datadir",
      "/geth",
      "--syncmode",
      "full",
      "--gcmode",
      "archive"
    ]
    ports:
      - $ESPRESSO_ZKEVM_L1_PORT:$ESPRESSO_ZKEVM_L1_PORT
    stop_signal: SIGKILL
