version: "3"
include:
  - docker-compose.yaml

services:
  orchestrator:
    image: ghcr.io/espressosystems/espresso-sequencer/orchestrator:main
    ports:
      - "$ESPRESSO_ORCHESTRATOR_PORT:$ESPRESSO_ORCHESTRATOR_PORT"
    environment:
      - ESPRESSO_ORCHESTRATOR_PORT
      - ESPRESSO_ORCHESTRATOR_NUM_NODES=5
      - ESPRESSO_ORCHESTRATOR_START_DELAY=5s
      - ESPRESSO_ORCHESTRATOR_MIN_PROPOSE_TIME
      - ESPRESSO_ORCHESTRATOR_MAX_PROPOSE_TIME
      - ESPRESSO_ORCHESTRATOR_NEXT_VIEW_TIMEOUT
      - RUST_LOG
      - RUST_LOG_FORMAT
    stop_grace_period: 1s
  da-server:
    image: ghcr.io/espressosystems/espresso-sequencer/web-server:main
    ports:
      - "$ESPRESSO_DA_SERVER_PORT:$ESPRESSO_WEB_SERVER_PORT"
    environment:
      - ESPRESSO_WEB_SERVER_PORT
      - RUST_LOG=error
    depends_on:
      orchestrator:
        condition: service_healthy
    stop_grace_period: 1s
  consensus-server:
    image: ghcr.io/espressosystems/espresso-sequencer/web-server:main
    ports:
      - "$ESPRESSO_CONSENSUS_SERVER_PORT:$ESPRESSO_WEB_SERVER_PORT"
    environment:
      - ESPRESSO_WEB_SERVER_PORT
      - RUST_LOG=error
    depends_on:
      orchestrator:
        condition: service_healthy
    stop_grace_period: 1s

  sequencer0:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    # Run consensus *plus* the sequencer API server.
    command: /bin/sequencer -- http -- query -- status -- submit
    ports:
      - "$ESPRESSO_SEQUENCER_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$ESPRESSO_DEMO_SEQUENCER_STAKING_PRIVATE_KEY_0
      - ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$ESPRESSO_DEMO_SEQUENCER_STATE_PRIVATE_KEY_0
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_ETH_ACCOUNT_INDEX
      - ESPRESSO_SEQUENCER_PREFUNDED_BUILDER_ACCOUNTS
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
      demo-l1-network:
        condition: service_healthy
    stop_grace_period: 1s
    extra_hosts:
      - "host.docker.internal:host-gateway"
  sequencer1:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$ESPRESSO_DEMO_SEQUENCER_STAKING_PRIVATE_KEY_1
      - ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$ESPRESSO_DEMO_SEQUENCER_STATE_PRIVATE_KEY_1
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_ETH_ACCOUNT_INDEX
      - ESPRESSO_SEQUENCER_PREFUNDED_BUILDER_ACCOUNTS
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
      sequencer0:
        condition: service_started
    stop_grace_period: 1s
    extra_hosts:
      - "host.docker.internal:host-gateway"
  sequencer2:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$ESPRESSO_DEMO_SEQUENCER_STAKING_PRIVATE_KEY_2
      - ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$ESPRESSO_DEMO_SEQUENCER_STATE_PRIVATE_KEY_2
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_ETH_ACCOUNT_INDEX
      - ESPRESSO_SEQUENCER_PREFUNDED_BUILDER_ACCOUNTS
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
      sequencer0:
        condition: service_started
    stop_grace_period: 1s
    extra_hosts:
      - "host.docker.internal:host-gateway"
  sequencer3:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$ESPRESSO_DEMO_SEQUENCER_STAKING_PRIVATE_KEY_3
      - ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$ESPRESSO_DEMO_SEQUENCER_STATE_PRIVATE_KEY_3
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_ETH_ACCOUNT_INDEX
      - ESPRESSO_SEQUENCER_PREFUNDED_BUILDER_ACCOUNTS
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
      sequencer0:
        condition: service_started
    stop_grace_period: 1s
    extra_hosts:
      - "host.docker.internal:host-gateway"
  sequencer4:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$ESPRESSO_DEMO_SEQUENCER_STAKING_PRIVATE_KEY_4
      - ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$ESPRESSO_DEMO_SEQUENCER_STATE_PRIVATE_KEY_4
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_ETH_ACCOUNT_INDEX
      - ESPRESSO_SEQUENCER_PREFUNDED_BUILDER_ACCOUNTS
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
      sequencer0:
        condition: service_started
    stop_grace_period: 1s
    extra_hosts:
      - "host.docker.internal:host-gateway"
  commitment-task:
    image: ghcr.io/espressosystems/espresso-sequencer/commitment-task:main
    environment:
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_HOTSHOT_ACCOUNT_INDEX
      - ESPRESSO_SEQUENCER_HOTSHOT_ADDRESS
      - ESPRESSO_SEQUENCER_URL
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      sequencer0:
        condition: service_healthy
      demo-l1-network:
        condition: service_healthy
    stop_grace_period: 1s
    extra_hosts:
      - "host.docker.internal:host-gateway"
