#!/usr/bin/env bash
set -e

nix develop .#crossShell --ignore-environment --keep HOME --command cargo build --release

docker build -t ghcr.io/espressosystems/espresso-polygon-zkevm-demo/hermez-adaptor:main -f docker/hermez-adaptor.Dockerfile .
