#!/usr/bin/env bash
set -e

nix develop .#crossShell --ignore-environment --keep HOME --command cargo build --release

docker build -t ghcr.io/espressosystems/espresso-polygon-zkevm-demo/polygon-zkevm-adaptor:main -f docker/polygon-zkevm-adaptor.Dockerfile .
docker build -t ghcr.io/espressosystems/espresso-polygon-zkevm-demo/state-db:main -f docker/state-db.Dockerfile .
docker build -t ghcr.io/espressosystems/espresso-polygon-zkevm-demo/zkevm-node:main -f docker/node.Dockerfile .
docker build -t ghcr.io/espressosystems/espresso-polygon-zkevm-demo/zkevm-prover:main -f docker/prover.Dockerfile .