#!/usr/bin/env bash
set -euxo pipefail
HOST=$1

function copy() {
    # docker save $1 | ssh $HOST "cat - | docker import - $1"
    docker save $1 | ssh -C $HOST docker load
}

copy ghcr.io/espressosystems/zkevm-node:release-doppio-v1.0.0
copy ghcr.io/espressosystems/zkevm-node:release-doppio-v1.0.0
copy ghcr.io/espressosystems/geth-zkevm-contracts:release-doppio-v1.0.0

copy ghcr.io/espressosystems/espresso-sequencer/sequencer:release-doppio-v1.0.0
copy ghcr.io/espressosystems/espresso-sequencer/cdn-server:release-doppio-v1.0.0
copy ghcr.io/espressosystems/espresso-sequencer/polygon-zkevm-adaptor:release-doppio-v1.0.0

copy ghcr.io/espressosystems/espresso-polygon-zkevm-demo/polygon-zkevm-adaptor:release-doppio-v1.0.0
