#!/usr/bin/env bash
# This is an end to end test for the espresso sequencer polygon zkevm demo.
#
# It's intended to not requiring compilation or deployment of contracts.
#
# It requires curl, jq, just and docker to be installed.
set -euo pipefail

# Load env vars
set -a; source .env; set +a;

export ADDR=0x1234567890123456789012345678901234567890
export RPC_1=http://localhost:$ESPRESSO_ZKEVM_1_L2_PORT

echo "Requesting funds from faucet"
curl -s -X POST http://localhost:$ESPRESSO_ZKEVM_1_FAUCET_PORT/faucet/request/$ADDR > /dev/null

echo "Waiting for balance to be updated..."

function check_balance() {
    for RPC in $RPC_1; do
        while true; do
            balance=$(curl -s -X POST -H "Content-Type: application/json" --data "{\"jsonrpc\": \"2.0\", \"method\": \"eth_getBalance\", \"params\": [\"$ADDR\", \"latest\"], \"id\": 1}" $RPC | jq -r '.result')
            echo "$(date) checking balance for $RPC"
            if [ "$balance" != "0x0" ]; then
                echo "Balance updated for $RPC: $balance"
                break
            fi
            sleep 1
        done
    done
}
export -f check_balance
timeout 60 bash -c check_balance

echo "Success!"
