#!/usr/bin/env bash
# This script is WIP
#
# 1. run: docker compose up --force-recreate
#    in the espresso-sequencer repo.
# 2. Run this script.
# 3. run scripts/demo-test-end-to-end to test if it works.
set -euo pipefail

cargo run --bin deploy -- --hotshot-address 0x5fbdb2315678afecb367f032d93f642f64180aa3 \
    --deploy --polling-interval 1000 --account-index 10

docker compose --profile zkevm1 zkevm1-preconfirmations \
    --env-file .env --env-file deployment.env up --force-recreate
