#!/usr/bin/env bash
# This script is WIP
#
# 1. run: docker compose up --force-recreate
#    in the espresso-sequencer repo.
# 2. Run this script.
# 3. run scripts/demo-test-end-to-end to test if it works.
set -euo pipefail

cargo run --bin deploy -- --hotshot-address 0x5fbdb2315678afecb367f032d93f642f64180aa3
docker compose --profile zkevm1 -f zkevm-on-espresso-compose.yaml \
    --env-file zkevm-on-espresso.env --env-file deployment.env up --force-recreate
