name: Lint

on:
  push:
    branches:
      - main
      - release-*
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  pull_request:
    branches:
  workflow_dispatch:

env:
  RUSTFLAGS: "--cfg async_executor_impl=\"async-std\" --cfg async_channel_impl=\"async-std\""
  RUST_LOG: info,libp2p=off

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/espressosystems/devops-rust:stable
    steps:

      - uses: styfle/cancel-workflow-action@0.11.0
        name: Cancel Outdated Builds
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      # The error is probably due to another CI run having changed the permissions.
      - name: Prevent git permission errors
        run: |
          git config --global --add safe.directory /__w/espresso-polygon-zkevm-demo/espresso-polygon-zkevm-demo
          git config --global --add safe.directory /__w/espresso-polygon-zkevm-demo/espresso-polygon-zkevm-demo/zkevm-contracts
          git config --global --add safe.directory /__w/espresso-polygon-zkevm-demo/espresso-polygon-zkevm-demo/zkevm-node

      - uses: actions/checkout@v3
        name: Checkout Repository
        with:
          submodules: true

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching

      - name: Format Check
        run: cargo fmt -- --check

      - uses: actions-rs/clippy-check@v1
        name: Clippy
        with:
          token: ${{ github.token }}
          args: --workspace --all-features --all-targets -- -D warnings

      - name: Audit
        run: cargo audit --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2022-0093 --ignore RUSTSEC-2023-0052 --ignore RUSTSEC-2023-0053 --ignore RUSTSEC-2023-0065 --ignore RUSTSEC-2024-0003
