name: Postgres state-db docker
on:
  push:
    branches:
      - main
      - release-*
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  pull_request:
    branches:
  workflow_dispatch:

jobs:
  state-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Repo
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker metadata
        uses: docker/metadata-action@v4
        id: state-db-metadata
        with:
          images: ghcr.io/${{ github.repository_owner }}/espresso-polygon-zkevm-demo/state-db

      - name: Build and push state-db docker
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./docker/state-db.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.state-db-metadata.outputs.tags }}
          labels: ${{ steps.state-db-metadata.outputs.labels }}
